image: node
stages:
  - build
  - test
build:
  stage:
    - build
  script:
    - 'cd NewsApp_UI/'
    - 'npm install'
    - 'npm run build'
test:
  stage:
    - test
  script:
    - 'cd NewsApp_UI/'
    - 'npm install'
    - 'npm run test'