image: node
stages:
  - build
  - test
include: '/NewsApp_UI/package.json'
build:
  stage:
    - build
  script:
    - 'npm install'
    - 'npm run build'
test:
  image: newsui
  stage:
    - test
  script:
    - 'npm install'
    - 'npm run test'