image: node
stages:
  - build
  - test
build:
  stage:
    - build
  CMD: ["cd", "NewsApp_UI/"]
  script:
    - 'npm install'
    - 'npm run build'
test:
  stage:
    - test
  script:
    - 'npm install'
    - 'npm run test'