image: node
stages:
  - build
  - test
build:
  stage:
    - build
  include:
    - local: /NewsApp_UI
  script:
    - 'npm install'
    - 'npm run build'
test:
  image: newsui
  stage:
    - test
  include:
    - local: /NewsApp_UI
  script:
    - 'npm install'
    - 'npm run test'