image: node
stages:
  - build
  - test
 before_script:
    - cd NewsApp_UI
build:
  stage:
    - build
  script:
    - 'npm install'
    - 'npm run build'
test:
  image: newsui
  stage:
    - test
  script:
    - 'npm install'
    - 'npm run test'